# Generated by Django 4.1.3 on 2022-11-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("nationality", models.CharField(max_length=200)),
                ("descriptio", models.TextField()),
            ],
        ),
    ]
