# Generated by Django 4.1.3 on 2022-11-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_author_options_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="creation_date",
            field=models.DateField(auto_now=True, verbose_name="Creation Date"),
        ),
        migrations.AddField(
            model_name="book",
            name="creation_date",
            field=models.DateField(auto_now=True, verbose_name="Creation Date"),
        ),
        migrations.RemoveField(
            model_name="book",
            name="author_id",
        ),
        migrations.AddField(
            model_name="book",
            name="author_id",
            field=models.ManyToManyField(to="book.author"),
        ),
    ]
